import asyncio
import runpod
import base64
import os
import tempfile
from argparse import Namespace
from pydub import AudioSegment
import shutil
import json
import time

from pipeline import SonicPipelineWrapper
from models import SonicRequest, SonicResponse
from output import send_to_telegram, upload_video_to_vk, upload_to_storage
import concurrency

# Initialize pipeline eagerly at module load time, before RunPod starts accepting jobs.
# This prevents the concurrency modifier from seeing GPU=0% during model loading
# and incorrectly allowing multiple jobs to start simultaneously.
print("Initializing Sonic pipeline...")
_pipe = SonicPipelineWrapper(device_id=0)
print("Sonic pipeline ready.")


def get_pipe():
    return _pipe


async def generator_handler(job):
    try:
        t_total_start = time.time()

        # Parse input data
        job_input = job.get("input", {})
        
        # Parse using Pydantic model
        try:
            request = SonicRequest(**job_input)
        except Exception as e:
            return {"output": {"error": f"Invalid request: {str(e)}"}}

        # Create temp directory for files
        temp_dir = tempfile.mkdtemp()

        # Save base64 image to file
        image_data = request.image_input.base64
        image_filename = request.image_input.filename
        image_path = os.path.join(temp_dir, image_filename)
        with open(image_path, "wb") as f:
            f.write(base64.b64decode(image_data))

        # Save base64 audio to file
        audio_data = request.audio_input.base64
        audio_filename = request.audio_input.filename
        audio_path = os.path.join(temp_dir, audio_filename)
        with open(audio_path, "wb") as f:
            f.write(base64.b64decode(audio_data))

        # Convert audio from mp3 to wav if needed
        t_decode_end = time.time()
        print(f"[TIMING] base64 decode + file write: {t_decode_end - t_total_start:.2f}s")

        if audio_filename.lower().endswith('.mp3'):
            try:
                mp3_path = audio_path
                audio_path = os.path.join(temp_dir, os.path.splitext(audio_filename)[0] + '.wav')
                AudioSegment.from_mp3(mp3_path).export(audio_path, format="wav")
                print(f"Converted MP3 to WAV: {audio_path}")
            except ImportError:
                print("Warning: pydub not installed. MP3 to WAV conversion failed.")
            except Exception as e:
                print(f"Error converting MP3 to WAV: {str(e)}")

        # Create output path
        output_path = os.path.join(temp_dir, "output.mp4")

        # Get pipeline and process
        pipe = get_pipe()
        
        # Preprocess
        t_preprocess_start = time.time()
        face_info = pipe.preprocess(image_path, expand_ratio=0.5)
        print(face_info)
        print(f"[TIMING] preprocess (face detect): {time.time() - t_preprocess_start:.2f}s")
        
        if face_info['face_num'] < 0:
            raise Exception("No face detected")
        
        # Crop if requested
        image_path_to_use = image_path
        if request.crop:
            crop_image_path = image_path + '.crop.png'
            pipe.crop_image(image_path, crop_image_path, face_info['crop_bbox'])
            image_path_to_use = crop_image_path
        
        # Process video
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        t_inference_start = time.time()
        result = pipe.process(
            image_path_to_use, 
            audio_path, 
            output_path, 
            min_resolution=512, 
            inference_steps=request.inference_steps, 
            dynamic_scale=request.dynamic_scale
        )
        print(f"[TIMING] inference + ffmpeg: {time.time() - t_inference_start:.2f}s")
        
        if result != 0:
            raise Exception("Video processing failed")

        # Initialize response
        response_data = {}

        # Determine output method based on request parameters
        if request.telegram:
            # Send to Telegram
            file_id = await send_to_telegram(
                bot_token=request.telegram.bot_token,
                user_id=request.telegram.user_id,
                video_path=output_path
            )
            response_data["telegram_file_id"] = file_id
        
        elif request.vk:
            # Send to VK
            message_id = upload_video_to_vk(
                video_path=output_path,
                group_token=request.vk.group_token,
                user_id=request.vk.user_id,
                title="Sonic Video",
                description="Generated by Sonic"
            )
            response_data["vk_message_id"] = message_id
        
        elif request.storage:
            # Upload to S3 storage
            storage_url = upload_to_storage(
                file_path=output_path,
                endpoint=request.storage.endpoint,
                bucket=request.storage.bucket,
                access_key=request.storage.access_key,
                secret_key=request.storage.secret_key
            )
            response_data["storage_url"] = storage_url
        
        else:
            # Return base64 encoded video
            t_encode_start = time.time()
            with open(output_path, "rb") as f:
                video_data = base64.b64encode(f.read()).decode('utf-8')
            print(f"[TIMING] base64 encode video: {time.time() - t_encode_start:.2f}s")
            response_data["base64"] = video_data

        # Clean up temporary files
        try:
            shutil.rmtree(temp_dir, ignore_errors=True)
        except Exception as cleanup_error:
            print(f"Error cleaning up temporary files: {str(cleanup_error)}")

        print(f"[TIMING] total job: {time.time() - t_total_start:.2f}s")
        return {"output": response_data}

    except Exception as e:
        return {"output": {"error": str(e)}}


runpod.serverless.start(
    {
        "handler": generator_handler,
        "concurrency_modifier": concurrency.adjust_concurrency,
    }
)
