import os
import requests
from typing import Optional


def upload_video_to_vk(
    video_path: str,
    group_token: str,
    user_id: str,
    title: str = "Sonic Video",
    description: str = "Generated by Sonic"
) -> Optional[str]:
    """
    Upload video to VK and send to user.
    
    Args:
        video_path: Path to video file
        group_token: VK group access token
        user_id: VK user ID to send to
        title: Video title
        description: Video description
        
    Returns:
        message_id: VK message ID if successful, None otherwise
    """
    # Step 1: Get upload server URL
    get_upload_url_url = "https://api.vk.com/method/video.save"
    params_save = {
        "access_token": group_token,
        "v": "5.131",
        "name": title,
        "description": description,
        "is_private": 1,
        "wallpost": 0
    }
    
    response = requests.get(get_upload_url_url, params=params_save)
    save_data = response.json()
    
    if "error" in save_data:
        print(f"VK save error: {save_data['error']}")
        return None
    
    upload_url = save_data["response"]["upload_url"]
    video_id = save_data["response"]["video_id"]
    owner_id = save_data["response"]["owner_id"]
    
    # Step 2: Upload video file
    with open(video_path, 'rb') as video_file:
        files = {'video_file': video_file}
        upload_response = requests.post(upload_url, files=files)
    
    if upload_response.status_code != 200:
        print(f"VK upload error: {upload_response.text}")
        return None
    
    # Step 3: Send video to user via messages.send
    attach = f"video{owner_id}_{video_id}"
    send_message_url = "https://api.vk.com/method/messages.send"
    params_send = {
        "access_token": group_token,
        "v": "5.131",
        "user_id": user_id,
        "attachment": attach,
        "random_id": int(os.urandom(16).hex(), 16)
    }
    
    response = requests.get(send_message_url, params=params_send)
    message_data = response.json()
    
    if "error" in message_data:
        print(f"VK message error: {message_data['error']}")
        return None
    
    return str(message_data["response"])
